version: '3.9'

services:
    admin:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        depends_on:
            - admin_db

    admin_db:
        image: mysql:5.7.22
        environment:
            MYSQL_DATABASE: admin
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - "33060:3306"

